---
title: "GHG Packed Circles"
author: "Kaydee S. Barker"
date: "2024-02-29"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}

rm(list=ls()) #clear global environment/workspace
knitr::opts_chunk$set(echo = FALSE, message = FALSE) #set echo and message to false universally

```

```{r load libraries, message=FALSE}

library(readODS) #read ods files
library(readxl) #reads excel files
library(tidyverse) #Tidy packages
library(dplyr) #lots of functions - data manipulation
library(janitor) #helps with data cleaning
library(data.tree) #transform df or file to data tree
library(circlepackeR) #circle packing (install with Github)
library(htmlwidgets) #save html widgets

```

```{r}

#Map loop to download UK 2022 data from the UK Department for Energy Security and Net Zero
downloaded <- file.exists("UKGHG_2022.ods") #checks if file is downloaded in working directory
if(downloaded != T){ #if downloaded is not true
  map2("https://assets.publishing.service.gov.uk/media/65c0d54663a23d000dc821ca/final-greenhouse-gas-emissions-2022-by-source-dataset.ods", #update this link when new data available
                         "UKGHG_2022.ods", download.file)} #else{print('data downloaded')} #name and download or print

#Read in ods file
GHG_UK22 <- read_ods(
  path = "UKGHG_2022.ods",
  sheet = 1, #define tab/sheet to read
  col_names = TRUE, #use header row for column names
  col_types = NULL, #guess data types
  na = "", #treat blank cells as NA
  skip = 0, #don't skip rows
  formula_as_formula = FALSE, #values only
  range = NULL, 
  row_names = FALSE, #no row names
  strings_as_factors = TRUE) %>% #use factors
  clean_names() %>% #clean column names to lowercase, with underscores
  separate_wider_delim(source, delim = " - ", #separate source, define delimiter as " - "
                       names = c("source_1", "source_2", "source_3"), #name new columns
                       too_few = "align_start", too_many = "merge", #what to do with fewer or more than 3
                       cols_remove = FALSE) %>% #keep original column
  separate_wider_delim(tes_category, delim = " - ", #separate category, define delimiter as " - "
                       names = c("category_1", "category_2"), #name new columns
                       too_few = "align_start", too_many = "merge", #what to do with fewer or more than 2
                       cols_remove = FALSE) %>% #keep original column
  separate_wider_delim(activity, delim = " - ", #separate activity, define delimiter as " - "
                       names = c("activity_1", "activity_2"), #name new columns
                       too_few = "align_start", too_many = "merge", #what to do with fewer or more than 2
                       cols_remove = FALSE) %>% #keep original column
  replace(is.na(.), "") #get rid of NA values, input blank



#Newest years only 
#UK-wide dataset
GHG_UK2022 <- GHG_UK22 %>%
  filter(year == "2022") #%>%
  #filter(tes_sector != "LULUCF") #filter out LULUCF to see if negative values impact things

GHG_UK2022pos <- GHG_UK2022 %>%
  filter(emissions_mt_co2e >= "0") #subset filter only positive values


#Simplify
GHG_simp <- GHG_UK2022 %>%
  group_by(tes_sector, tes_subsector, tes_category, category_2, category_1, activity, ghg_grouped) %>%
  summarize(Temissions = sum(emissions_mt_co2e, na.rm = TRUE)) %>%
  replace(is.na(.), "") %>%
  filter(Temissions >= "0") #subset filter only positive values

```

```{r data tree, warning=FALSE}

#Make data tree

#Define hierarchy as pathString
GHG_UK22$pathString <- paste("UK", 
                            GHG_UK22$tes_sector, 
                            GHG_UK22$tes_subsector, 
                            GHG_UK22$category_2,
                            GHG_UK22$category_1,
                            #GHG_UK22$activity,
                            sep = "/")

#Convert to nodes
GHGtree <- as.Node(GHG_UK22)

#print(GHGtree, "emissions_mt_co2e", limit=20)


#Define hierarchy as pathString
GHG_UK2022pos$pathString <- paste("UK", 
                            GHG_UK2022pos$tes_sector, 
                            GHG_UK2022pos$tes_subsector, 
                            #GHG_simp$tes_category,
                            GHG_UK2022pos$category_2,
                            GHG_UK2022pos$category_1,
                            GHG_UK2022pos$activity,
                            sep = "/")
#Convert to nodes
GHGtree2022 <- as.Node(GHG_UK2022pos)

#print(GHGtree2022, "Temissions", limit=20)


#Define hierarchy as pathString
GHG_simp$pathString <- paste("UK", 
                            GHG_simp$tes_sector, 
                            GHG_simp$tes_subsector, 
                            #GHG_simp$tes_category,
                            GHG_simp$category_2,
                            GHG_simp$category_1,
                            GHG_simp$activity,
                            sep = "/")

#Convert to nodes
GHGsimptree <- as.Node(GHG_simp)


```

### Packed Circles

```{r packed circles, warning=FALSE}

circles <- circlepackeR(GHGtree2022, size = "emissions_mt_co2e", color_min = "hsl(56,80%,80%)", color_max = "hsl(341,30%,40%)")

circles

#circlepackeR(GHGsimptree, size = "Temissions", color_min = "hsl(56,80%,80%)", color_max = "hsl(341,30%,40%)")

saveWidget(circles, file=paste0( getwd(), "circular_packing.html"))

```


